### ISSUE TITLE
No sound when showControls is set to false

### ISSUE THREAD

**Issue by inorbita** [pupunzi/jquery.mb.vimeo_player#11]
Hi,

there is no sound when when showControls is set to false. Whether mute is set to true or false has no influence. And sound can't be turned on or toggled with a button either. Is this as intended or perhaps a bug?

What I try to achieve:

- no video controls
- sound muted by default (via mute: true)
- sound toggle button.

This is my code: 

```
<section class="hero">
  <div id="P1" class="player" data-property="{videoURL:'https://vimeo.com/247877419',containment:'.has-video',showControls:false,optimizeDisplay:true,stopMovieOnBlur:true,mute:true,autoPlay:true,loop:true}">
  </div>
  <button onclick="jQuery('#P1').v_toggle_volume()">unmute/unmute</button>
  <button onclick="jQuery('#P1').v_toggle_play()">play/pause</button>
</section>
```

**Comment by pupunzi** [comment]
With the latest 1.1.3 release this issue should be fixed.
https://github.com/pupunzi/jquery.mb.vimeo_player/archive/1.1.3.zip

**Comment by Le-future** [comment]
Hello!

Great plugin as always, even if for me, the sound issue is still present so, what I did is to add in my CSS the display none on the following rule : 

`.vimeo_player_bar .buttonBar {
    ...
    display: none !important;
}`

Hope this helps for the time being 😉
